### ISSUE TITLE
No dirt block spawns

### ISSUE THREAD

**Issue by SimonMeskens** [Vashmeed/nVoid#2]
I added the mod, spawned and died, and kept dying. Seems like the single dirt block thing doesn't work.

Also, small request, could you make a config option where it spawns you on a chest instead? And then have a list of items that spawns in the chest. That way, we can use this to make skyblock packs.

Thanks for the good work

**Comment by Deshiba** [comment]
The chest idea seems nice. It would be fabulous if we could detect the minecraft option for "Bonus Chest" for this. When turned on a chest could generate, with the "Bonus Chest" inventory. 

The bonus chest loot can already be manipulated trough Forge Hooks:
http://minecraftforgetutorials.weebly.com/chest-gen-hooks.html

**Comment by SimonMeskens** [comment]
Yeah, that sounds wonderful. I'd do a PR myself, but I'm balls deep in balancing a skyblock pack right now.

**Comment by Vashmeed** [comment]
Thanks for reporting this bug! This will be fixed in the next commit.
As for the Bonus Chest option, I'll look into adding that to the 1.0 release.

Thank you two so much for your feedback and suggestions.
