### ISSUE TITLE
Interested in port to 1.12?

### ISSUE THREAD

**Issue by dizzyd** [Vashmeed/nVoid#6]
Hi @Vashmeed!

I've ported this forward to 1.12 and was wondering if you might be interested in the changes? Let me know and I'll submit a PR for it. This is a super useful mod for testing oregen changes, so I'd love to see it updated. :)

**Comment by Vashmeed** [comment]
Hey @dizzyd!

That sounds awesome and I imagine will help a lot of people out!

Please do request a PR whenever you can =]

**Comment by dizzyd** [comment]
Hi @Vashmeed!

I submitted the PR earlier this morning. Please let me know if you have any concerns/issues.
